Use editor to provide PR metadata when generating PR url's

diff --git a/bin/gh-pr b/bin/gh-pr
--- a/bin/gh-pr
+++ b/bin/gh-pr
@@ -13,6 +13,50 @@ if [ "$1" == "--help" -o "$1" == '-h' ]; then
   exit
 fi
 
+# This uses EDITOR as editor, or vi if EDITOR is null or unset
+EDITOR=${EDITOR:-vi}
+
+die() {
+  # die <string>
+  (($#)) && printf >&2 '%s\n' "$@"
+  exit 1
+}
+
+urlencode() {
+    # urlencode <string>
+    old_lc_collate=$LC_COLLATE
+    LC_COLLATE=C
+
+    local length="${#1}"
+    for (( i = 0; i < length; i++ )); do
+        local c="${1:i:1}"
+        case $c in
+            [a-zA-Z0-9.~_-]) printf "$c" ;;
+            *) printf '%%%02X' "'$c" ;;
+        esac
+    done
+
+    LC_COLLATE=$old_lc_collate
+}
+
+prData(){
+  local temp=$(mktemp) || die "Can't create temp file"
+  local ret_code
+  echo "$(git log -1 --pretty=%B)" > $temp
+
+  if "$EDITOR" -- "$temp" && [[ -s $temp ]]; then
+    content=$(< "$temp")
+    title=$(urlencode "$(head -n 1 "$temp")")
+    body=$(urlencode "$(tail -n +2 "$temp")")
+
+    ret_code=0
+  else
+    ret_code=1
+  fi
+  rm -f -- "$temp"
+  return "$ret_code"
+}
+
 # Run through all remotes looking for a github repository. Bail when found.
 remotes="origin $(git remote)"
 for remote in $remotes;
@@ -36,8 +80,7 @@ done
 
 # No github.com remotes exists. Death.
 if [ -z "$url" ]; then
-  echo "error: no github.com git remotes found" 1>&2
-  exit 1
+  die "error: no github.com git remotes found"
 fi
 
 # Axe the .git suffix if there is one. Remove trailing slashes.
@@ -51,8 +94,9 @@ branch=${1:-"master"}
 if git rev-parse "refs/remotes/origin/$branch" 1>/dev/null 2>&1; then
   current_branch=$(git branch | sed -n '/\* /s///p')
 
-  echo "$url/compare/$branch...$current_branch"
+  prData || die "Creating pull request aborted."
+
+  echo "$url/compare/$branch...$current_branch?expand=1&title=$title&body=$body"
 else
-  echo "error: branch '$branch' does not exist on the origin remote." 1>&2
-  echo "       try again after pushing the branch"
+  die "error: branch '$branch' does not exist on the origin remote. Try again after pushing the branch"
 fi
